---
title: Plant breeding innovation trajectories at LGUs
author: Liza Wood, Adam Vera, Victoria Fletcher 
date: 2023-09-27

github-repo: liza-wood/lgu-plant-breeding
url: "https://liza-wood.github.io/lgu-plant-breeding/"

site: "bookdown::bookdown_site"
knit: "bookdown::render_book"

output:
  bookdown::gitbook:
    css: styling.css
    config:
      code_folding: show
      toc: 
        before: |
          <li><a href="https://liza-wood.github.io/">
                    </a></li>
          <li><a href="./" style="font-size: 16px">Plant breeding trajectories</a></li>
        after: |
          </a>
        collapse: section
      sharing: no
      view: https://github.com/liza-wood/lgu-plant-breeding/blob/master/%s
      edit: https://github.com/liza-wood/lgu-plant-breeding/edit/master/%s
---

# Overview {-}

This webpage presents summaries of a research effort to bring together several data sets related to plant variety development at Land Grant Universities (LGUs) in the United States. This work groups data into four major categories:  

1. **Plant intellectual property owned by LGUs:** These data are from the USDA PVPO and US PTO via `patentR` and `patentsview` packages that wrap around the Patents View API, filtered to match Land Grant University names.  
2. **LGU plant variety licensing agreements:** These data were requested from all 50 1862 LGUs. The focus was on licensing agreements made between 2000-2020, with data on what plant variety was licensed, to whom, and with what restrictions. 
3. **Licensee profiles:** The license data collected from Part 2 were used to create an index of licensees. Licensees were searched in the Dun & Bradstreet Hoovers database, which includes company profile data, to identify the location, size (sales and employees), and co-ownership structure of the licensees. 
4. **LGU awards.** These data were requested from 25 LGUs (respondents to licensing request) for the time span 2000-2020. The focus was on awards data to the university's closest thing to a College of Agriculture, which would likely include breeders as well as a host of other researchers.  

The analysis for these data are ongoing, and what follows are preliminary descriptive summaries of the data we have collected and cleaned. Note: There are still several errors and the data presented is still not entirely clean, so please excuse any errors and take results as preliminary. 

## Citation {-} 

Please use the following citation:

Wood, L., Vera, A., & Victoria, F. (2023). Plant breeding innovation trajectories at LGUs. https://doi.org/10.5281/zenodo.14537188

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-HJX1JG1FCV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-HJX1JG1FCV');
</script>